// Canonical tool colour system for all type-tools sites.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/lib/toolColors.ts instead.

/** All tool IDs in canonical order. Append new tools at the end — existing hues stay stable. */
export const TOOL_IDS = [
	'axisRhythm',
	'fitFlush',
	'fitWidth',
	'floodText',
	'glyphShaper',
	'hoverBoldly',
	'magnetType',
	'opszStepper',
	'opticalMargin',
	'ragtooth',
	'speechType',
	'stabilType',
	'steadyGray',
	'textBreath',
	'typsettle',
	'vfClamp',
	'wrapType',
] as const

export type ToolId = typeof TOOL_IDS[number]

/** Golden angle in degrees — distributes hues so each new tool fills the largest remaining gap. */
const GOLDEN_ANGLE = 137.508

function hueForIndex(index: number): number {
	return Math.round((index * GOLDEN_ANGLE) % 360)
}

/** --background oklch value for a given tool ID. */
export function toolBg(toolId: string): string {
	const index = (TOOL_IDS as readonly string[]).indexOf(toolId)
	return `oklch(0.10 0.12 ${index >= 0 ? hueForIndex(index) : 0})`
}

/** --btn-bg oklch value for a given tool ID. */
export function toolBtnBg(toolId: string): string {
	const index = (TOOL_IDS as readonly string[]).indexOf(toolId)
	return `oklch(0.18 0.07 ${index >= 0 ? hueForIndex(index) : 0})`
}

/** --foreground oklch value for a given tool ID — light, legible, hue-tinted to match the background. */
export function toolFg(toolId: string): string {
	const index = (TOOL_IDS as readonly string[]).indexOf(toolId)
	return `oklch(0.93 0.03 ${index >= 0 ? hueForIndex(index) : 0})`
}
