// SiteFooter — shared footer for all type-tools sites.
// Synced automatically by type-tools/scripts/sync-sites.mjs.
// DO NOT edit this file inside a submodule — edit type-tools/shared/components/SiteFooter.tsx instead.

import Script from 'next/script'
import ToolDirectory from "./ToolDirectory"

interface SiteFooterProps {
	/** ID of the current tool — passed to ToolDirectory to suppress its own link */
	current: string
	/** npm package version (imported from root package.json) */
	npmVersion: string
	/** site version (imported from site/package.json) */
	siteVersion: string
}

/** Shared footer: tool directory grid, Liiift link, version numbers, and GA4 analytics. */
export default function SiteFooter({ current, npmVersion, siteVersion }: SiteFooterProps) {
	const gaId = process.env.NEXT_PUBLIC_GA_ID
	return (
		<footer className="w-full max-w-2xl lg:max-w-5xl flex flex-col gap-6 pt-8 border-t border-white/10 text-xs">
			{gaId && <>
			<Script src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`} strategy="afterInteractive" />
			<Script id="ga-init" strategy="afterInteractive">{`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${gaId}')`}</Script>
		</>}
			<ToolDirectory current={current} />
			<hr className="border-white/10" />
			<div className="grid grid-cols-2 sm:grid-cols-4 gap-x-8 opacity-50">
				<a
					href="https://liiift.studio"
					target="_blank"
					rel="noopener noreferrer"
					className="hover:opacity-100 transition-opacity"
				>
					liiift.studio
				</a>
				<span className="sm:col-start-4 tabular-nums">
					npm v{npmVersion} · site v{siteVersion}
				</span>
			</div>
		</footer>
	)
}
